version: '3.7'

services:
  mongodb:
    image: mongo:latest
    mem_limit: 512m
    container_name: mongodb

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: welcome1
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: