version: '3.5'
services:

  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: productsdb
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: welcome1
      PG_DATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

  #pgadmin4:
  #  image: dpage/pgadmin4
  #  container_name: pgadmin4
  #  restart: unless-stopped
  #  links:
  #    - postgres
  #  depends_on:
  #    - postgres
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: dougdb@mail.com
  #    PGADMIN_DEFAULT_PASSWORD: welcome1
  #  ports:
  #    - "12500:80"

volumes:
  postgres: